spring:
  application:
    name: ListaContatos
  data:
    mongodb:
      uri: mongodb://localhost:27028/ListaContatos
app:
  config:
    passVar:  ${PASS}

springdoc:
  override-with-generic-response: false
